### ISSUE TITLE
no scrolling with revealjs output

### ISSUE THREAD

**Issue by PierreSolomon** [shafayetShafee/code-fullscreen#5]
Hello,

I looked at your example and in the html format you can scroll on the code if it is too long to be show on the screen. However, it isn't possible for the revealjs format.
Is it a bug?

**Comment by shafayetShafee** [comment]
Can you provide me with a reproducible example? When I view [this demo](https://shafayetshafee.github.io/code-fullscreen/example_revealjs.html) on my desktop, I can see the scrollbar.

**Comment by PierreSolomon** [comment]
When I look at the same demo, I can see the scrollbar but only if I don't activate the fullscreen. If I activate it I don't see the scrollbar and only the first 45 lines and a part of the line 46 of the code are show. I also can't scroll down.
I'm on windows 11 and I'm using firefox 110.0.1 to view the demo.

**Comment by shafayetShafee** [comment]
Okay, now I am facing the same issue you mentioned while viewing the demo with firefox. But it is working well with google chrome. Thanks for reporting. Let me investigate the issue.

**Comment by shafayetShafee** [comment]
@PierreSolomon, install the extension again. The raised issue should be fixed for Firefox now 😊. Let me know if there are still problems.

**Comment by PierreSolomon** [comment]
It is fixed on my side and there doesn't seem to be any problem.
Thank you for the extension
